### ISSUE TITLE
Camera mouselook drifts

### ISSUE THREAD

**Issue by DaedalusMDW** [DaedalusMDW/bge_game-3.0_template#7]
![8123b162922cf473068d909d8557cab11a96527d](https://user-images.githubusercontent.com/26656082/45810844-40e79a00-bc91-11e8-8c9f-7dafa5f5d690.jpeg)
self explanatory.

**Comment by CYNIC78** [comment]
This issue is appearing only when i launch game inside blender 2.79 (standalone player) and .exe version (2.74) hasn't this problem.

**Comment by DaedalusMDW** [comment]
it looks like its on one axis, this is different then the usual resolution glitch.  i cant reproduce on linux, windows, upbge, and bfbge.

could it be a rogue game controller?  by default, the keymap is configured for a gamepad.  i think the console prints connected controllers.

**Comment by CYNIC78** [comment]
> it looks like its on one axis, this is different then the usual resolution glitch. i cant reproduce on linux, windows, upbge, and bfbge.
> 
> could it be a rogue game controller? by default, the keymap is configured for a gamepad. i think the console prints connected controllers.
> 
> what is your resolution btw?

Well, in blender itself resolution set to standart 1920x1080, but when i launch standalone player it changed to 1190x669. It seems like this is the problem. In .exe version resolution is 1600x600. How do i change resolution in launcher to see how it will influence on camera with different resolution?

**Comment by DaedalusMDW** [comment]
ah ha, i get it!  it must be an issue with non- standard resolutions.

delete your graphics.cfg or type "resolution -?" to see the options

"-l" 1280x720
"-m"1600x900
"-h" 1920x1080
"-x # -y #" for custom
"-f" fullscreen toggle

**Comment by CYNIC78** [comment]
> ah ha, i get it! it must be an issue with non- standard resolutions. ill see if i can fix it.
> 
> delete your graphics.cfg or type "resolution -?" to see the options
> 
> "-l" 1280x720
> "-m"1600x900
> "-h" 1920x1080
> "-x # -y #" for custom
> "-f" fullscreen toggle
> 
> could you tell me if it does this in window mode?
> 
> this must have been the resolution it found and saved when you launched from embedded.

Yes, that fixed my problem. I just deleted Graphic.cfg (it had resolution1190x669). No more camera drift. In newly created graphic.cfg I have changed fullscreen to false (windowed mode) and have no drift aswell, even that resolution showing in right corner isn't 1920x1080 but 1916x1054, however no camera drift in game.

**Comment by DaedalusMDW** [comment]
it turns out its an issue with odd numbers.  since the mouse has no "center" it has to round to the nearest pixel.  ill see if i can fix that
